#------------------------------------------------------------------------------
# PAGER -- compiles the Executive Orders .csv file into a webpage for easy
#          reading.
#------------------------------------------------------------------------------

from datetime import datetime
from pytz import timezone
import pandas as pd
import subprocess

csv_path = "./executive-orders/eos.csv"
output_path = "./eos.html"
bill_dir = "executive-orders/"

#------------------------------------------------------------------------------

o = open(output_path, "w")

with open("./executive-orders/header", "r", errors="ignore") as f:
    for l in f.readlines(): print(l, end="", file=o)

df = pd.read_csv(csv_path)

headers = list(df.columns)
headers[-3:] = ["Status"] # cut off the last two columns, their data is displayed elsewhere

print("<table>\n\t<tr>", file=o)

for h in headers:
    print(f"\t\t<th>{h}</th>", file=o)

print("\t</tr>", file=o)

for i in range(len(df)):
    row = df.iloc[i].to_dict()
    print("\t<tr>", file=o)

    # f'<b>{row["Number"]}</b> &mdash;&nbsp; Signed {row["Date"]} by President {row["President"]}. &nbsp;&nbsp; \"{row["Title"]}\" &mdash; {row["Summary"]} Repeal information: <i>{row["Repealed"]}</i><br/>', file=o)
    print(f'\t\t<td id="number"><b>{row["Number"]}</b></td>', file=o)
    print(f'\t\t<td id="date"><a href="{row["SignageLink"]}" target="_blank">{row["Date"]}</a></td>', file=o)
    print(f'\t\t<td id="president">{row["President"]}</td>', file=o)
    print(f'\t\t<td id="title">\"<a href="{row["DocumentLink"]}" target="_blank">{row["Title"]}</a>\"</td>', file=o)
    print(f'\t\t<td id="summary">{row["Summary"]}</td>', file=o)
    print(f'\t\t<td id="repealed">{row["Repealed"]}</td>', file=o)
    # print(f'\t\t<td id="links"><a href="{row["DocumentLink"]}" target="_blank">Document</a><br/><br/><a href="{row["SignageLink"]}" target="_blank">Signing</a></td>', file=o)
    # print(f'\t\t<td id="messagelink"></td>', file=o)

    print("\t</tr>", file=o)

print("</table>", file=o)

t = datetime.now(timezone("US/Central"))
print(f'</body>\n<br/><br/>\n<footer style="color: #ddd;">\n\tLast updated {t.strftime("%m/%d/%y")} at {t.strftime("%H:%M %Z")}.\n This file is (<a href="https://wrzeczak.net/stolow/aggregator.py">semi-</a>) <a href="https://wrzeczak.net/stolow/pager.py">autogenerated</a>, please see the #sim-history channel for a GitHub link to the source, and notify @wrzeczak of any errors on the page. Thanks!</footer>', file=o) # print the footer, similarly to the header

subprocess.call(["cp", "-r", bill_dir, f"backup-{bill_dir}"])
subprocess.call(["diff", bill_dir, f"backup-{bill_dir}"])